### ISSUE TITLE
Recipient handler revert reason not showing up sometimes

### ISSUE THREAD

**Issue by tkporter** [hyperlane-xyz/hyperlane-explorer#33]
Example, mumbai -> goerli:
https://explorer.hyperlane.xyz/message/0xc809f5e01a53782be251ee9e39202ae9382ac541c74812007ea4b91a3df491aa

For some reason the revert reason isn't showing in the explorer, but it shows in the relayer:
```
ContractError(MiddlewareError(MiddlewareError(MiddlewareError(JsonRpcClientError(JsonRpcError(JsonRpcError { code: 3, message: \"execution reverted\", data: Some(String(\"0x815e1d64\")
```

Maybe related to the use of custom errors?

**Comment by jmrossy** [comment]
Thanks for the heads up, I'll look into it

**Comment by jmrossy** [comment]
@tkporter in the example you shared above, is "execution reverted" the info you're expecting to see in the Explorer or does the data field's hex contain some encoded string value? It doesn't seem to decode to anything AFAI can tell
