### ISSUE TITLE
Permissionless chain's aren't appearing

### ISSUE THREAD

**Issue by HariSeldon23** [hyperlane-xyz/hyperlane-explorer#46]
I've added a PI chain, however it's not appearing in the list of supported chains within the Explorer as per the below gif
![PI](https://github.com/hyperlane-xyz/hyperlane-explorer/assets/3041005/4a5a07b2-5add-4db6-991d-94d637b63e99)

Then the examples also don't take into account of the new Explorer type (Etherscan) 

https://docs.hyperlane.xyz/docs/build-with-hyperlane/explorer/configuring-pi-chains
![image](https://github.com/hyperlane-xyz/hyperlane-explorer/assets/3041005/537a93f1-0a16-489d-b8b9-2d78c563472b)

**Comment by HariSeldon23** [comment]
I guess this would relate to the `scraper` having support for the new chain in order to display the information. 

This would mean that people adding custom chains would need to be updated into the Hasura GraphQL endpoint which then the scraper would then to dynamically start scraping.

Although I could have misunderstood the architecture.

**Comment by avious00** [comment]
@HariSeldon23 Justin, hope we responded to you over telegram and helped resolve this issue. Closing this out because we're about to revamp our permissionless experience to be a lot easier.
